### ISSUE TITLE
refactor config mgmt on branch confignew

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#17]
see changes on branch confignew, needs to come alive and work with www_config_private

- info_incachain
- info_incasdk
on branch config new

has been prepared with right config file

purpose:

- all comes from config files
- dependencies are resolved on repo level

example see:
kristoftest dir on https://github.com/threefoldfoundation/www_config_private/tree/confignew

**Comment by MElborolossy** [comment]
# Updates:

- Collect the publisher configurations in the `ConfigRoot` in `publishconfig` struct variable.
- Rename init in model_nodejs to init_nodejs to be clear.
- Refactor the code to take the publisher configuration from a file if existed otherwise set it with the old values as default values.
- Remove unwanted function calls and variables that are no longer used.
- Make sure that all variables are named correctly after refactor.

# Need more info
- How to get the site config file name ? In the current situation, the site config file name must be sites.json

**Comment by MElborolossy** [comment]
## Updates:
After a call with Hamdy about this issue, I found the following:
- Append the `site_*.json` or `sites.json` to the `sites.json` which is on the remote server.
- Create a new logic if we want to delete any entry from sites.json

While I'm working on the previous points I found that publish_core needs a refactor also, still use old code.

**Comment by despiegk** [comment]
it does not have to work with the central server because that one needs refactoring anyhow

**Comment by despiegk** [comment]
cannot continue first need to finish gittools and path module

**Comment by MElborolossy** [comment]
Why PR #18 closed without merge? It contains all the new refactors
We don't need it anymore?
