### ISSUE TITLE
finish Gittools module [development_path_git]

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#22]
scan for TODO
create more tests

**Comment by MElborolossy** [comment]
We have an issue due to cycle import
After refactor, 
- `publisher_config/config.v` imports gittools module and use it inside `config_load` and `process_site_repo` functions
- `gittools/gittools.v`imports publisher_config and use it inside `new` and `init_codewww` functions
![image](https://user-images.githubusercontent.com/11272864/125263147-11ebb880-e303-11eb-9400-9dbdcbd229bf.png)

Suggestions:
1. Move functions from one module to another, so one module uses the other one
2. Separate the functions that cause this conflict in a new module
