### ISSUE TITLE
tests for doctree

### ISSUE THREAD

**Issue by mariobassem** [crystaluniverse/crystallib#309]
doctree needs to be able to walk over a directory, read and correctly parse all markdown files within the directory.

**Comment by mariobassem** [comment]
progress update:
- code is heavily outdated, it contains non-existent elements and mehods from the markdownparser, specifically the `Link` elements, which does not currently exist. i'll create a dummy link element for now to not-change code heavily until this is sorted.

**Comment by ashraffouda** [comment]
we need to know more about the terminologies used in the doctree because this is very hard to understand how it is going
for example the `tree` consists of (`collection`, `macroprocessor`)  and `collection` consists of 
```
pub struct Collection {
pub:
  name      string
  tree_name string
pub mut:
  title           string
  pages           map[string]&Page // markdown pages in collection
  files           map[string]&File
  images          map[string]&File
  external_pages  map[string]&Page
  external_files  map[string]&File
  external_images map[string]&File
  path            Path
  errors          []CollectionError
  state           CollectionState
  heal            bool
  tree            &Tree             @[str: skip]
}
```
we don't know anything about those properties what is `pages`,`files`, `external_pages` ...... 
also for other structs like `Page` and `File` itself 
@despiegk can u plz provide more specs about this?

**Comment by ashraffouda** [comment]
we tried to run the [tests](https://github.com/freeflowuniverse/crystallib/blob/6c3731684c32ef23c7fa67295d4c96434354dba4/crystallib/data/doctree/tree_test.v) and we found out that:
- it fails because the collection in the test has duplicate files in different [dirs](https://github.com/freeflowuniverse/crystallib/blob/6c3731684c32ef23c7fa67295d4c96434354dba4/crystallib/data/doctree/testdata/collections/examples/.collection). so what the doctree should do in this case? fail like what it is now or somehow handle these duplicates for example `examples/eth/account` and `examples/tfchain/account`
- if the parent dir contains `.collection` and one or more of it's children also contains `.collection` the doctree doesn't take those children collections into account and just deal with them as one collection related to the parent

**Comment by mariobassem** [comment]
- i commented any code that mentions the `Link` element, @despiegk  how should we proceed from here?
- regarding this (https://github.com/freeflowuniverse/crystallib/issues/309#issuecomment-1820911453), we separated the examples collection into multiple smaller collections to avoid duplicates for now.

**Comment by mariobassem** [comment]
@ashraffouda and I were trying to fix `DocTree` tests, and the `MDBook` struct relies heavily on the `Link` markdown element. I checked the `markdownparser` code and the `Link` element was commented here: https://github.com/freeflowuniverse/crystallib/blob/ec192a923c2f9b0298b021a8107cbc793b0a55e6/crystallib/data/markdownparser/elements/element_paragraph.v#L3

We need to know how should we treat links in md files? 
should it be treated as an element of a paragraph like old code did, or should it be in a separate `Link` element?

**Comment by despiegk** [comment]
- please check the table functionality, process has been implemented, see the todo
- implement & check link, code should be there +-, check TODO
- check the test from /archive/link_test.v and put in right dir
- check table test (once formatting done properly)
- do chart_parser test (in archive)

do on branch [development_markdown]

**Comment by mariobassem** [comment]
for the table parsing, the following inputs are tested against and are expected to succeed, but when parsed, an error is returned:
```
|   Column1   | Column2      | Column3    |
|-------------|--------------|------------|

error: table needs to have 3 rows at least
```

```
|   Column1   | Column2      | Column3    |
|-------------|--------------|------------|
|   Row1Col1  | 
|   Row2Col1  | Row2Col2     | Row2Col3   |

error: wrongly formatted row
```

```
|   Column1   | Column2      | Column3    |
|-------------|--------------|------------|
|   Row1Col1  | Row1Col2     | Row1Col3   | Row1Col4 |
|   Row2Col1  | Row2Col2     | Row2Col3   |

error: wrongly formatted row
```

Which path should we go with in each case?
I'll go with the current implementation in all cases until told otherwise.

**Comment by mariobassem** [comment]
i added all archived tests, updated them to match the current implementation.
