### ISSUE TITLE
hero mdbook URL format bug in conversion

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#408]
# Situation

Using hero mdbook, the URL conversion is not working optimally.

# Example

Working with "manual" book in https://git.ourworld.tf/tfgrid/info_tfgrid, URL formatting is not done properly.

The initial file is like this:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/66ef2ed8-4a51-4a96-885c-65eae153f869)

The conversion ends up like this:

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/a5a75fab-1225-4961-8a7a-22bccb600af0)

We see that (../knowledge_base/knowledge_base.md) stays the same.

Also the link (documentation.md) does not work, it works if it is (manual:documentation.md)

**Comment by mariobassem** [comment]
i noticed a lot of changes in the repo info_tfgrid repo, but i think i got the idea.
the problem is that links should point to which collection they reference, if not, it's assumed that they point to the current collection. 
in this case, the links (../knowledge_base/knowledge_base.md) and (../documentation/documentation.md) both reference documents that exist in other collections (knowledge_base, documentation), so they should reference the collection like (documentation:documentation)
there was a bug actually in parsing first link in a list, this is why the (../knowledge_bse/knowledge_base.md) link didn't change like other links after exporting, but it's fixed [here](https://github.com/freeflowuniverse/crystallib/pull/411)

**Comment by mik-tf** [comment]
Thanks that makes sense.

I will have to change the URl to collection:filename.md in all the files then.
