### ISSUE TITLE
current hero doesn't install right

### ISSUE THREAD

**Issue by mik-tf** [crystaluniverse/crystallib#417]
# Situation

As of the current hero, it does not install properly.

# Reproduce Steps

Follow the guide here: https://git.ourworld.tf/tfgrid/info_tfgrid/src/branch/main/docs/hero_mdbook_fullvm.md

This used to work. It doesn't anymore.

My old version of hero (some weeks ago) on a full vm still works. But not when I try to deploy a new vm and follow the same steps.

# Screenshots

![image](https://github.com/freeflowuniverse/crystallib/assets/77026219/66c09b11-6ada-427c-b9e8-55a18b46bdce)

**Comment by mik-tf** [comment]
@scottyeager found a fix: the link to download the hero installer was off.

Good one is:

https://raw.githubusercontent.com/freeflowuniverse/crystallib/development/scripts/installer_hero.sh

**Comment by scottyeager** [comment]
`installer_hero.sh` works, but it installs an old version. The real issue here is that the hero doesn't build in recent commits to the development branch. I was able to get a working build by rolling back and making a small change to fix one build error (that's on `development_mdbooktoml`). What's needed is to correct all build errors on the development branch.

**Comment by mik-tf** [comment]
@despiegk This would be the priority if it isnt fixed yet: make sure Hero installs with the current installer script. Read @scottyeager's comment for more info.

**Comment by mik-tf** [comment]
@despiegk this should be the priority, along with #428

Once those 2 issues are set, hero mdbook can be used to production and we'll have functioning mdbooks!

**Comment by despiegk** [comment]
the builder is working again, should be ok now
