### ISSUE TITLE
fix/check TFGrid client in Crystal

### ISSUE THREAD

**Issue by despiegk** [crystaluniverse/crystallib#438]
config mgmt class

* use config mgmt base class for TFGrid clients (so can remember e.g. private key, network, ...)

get the examples for deploy to work in V

* ~/code/github/freeflowuniverse/crystallib/examples/tfgrid/grid/examples/vm_high_level/deploy_vm_high_level.v
* looks like most examples not working
* if needed make installer for the golang components as needed (e.g. the driver)

example in wrong location

* get the tfgrid deploy examples for deploy to work
* /Users/despiegk/code/github/freeflowuniverse/crystallib/crystallib/threefold/grid/example

## checklist

* [x] can deploy VM
* [x] can get to VM over mycelium
* [x] can deploy ZDB
* [x] can deploy webgateway based on DNS name and subname
* [x] can do queries to explorer to be able to fund node
* [x] can get monitor info from node
* [x] can talk over rmb to node and all is documented

**Comment by renauter** [comment]
When I checkout crystallib repo and try to run some examples I always get errors related to module importation.
I don't get why most import are done like this
~~~vlang
import freeflowuniverse.crystallib.xxx
~~~
Since the root directory of a V project is defined by the presence of the v.mod file, which in our case is `crystallib/crystallib`, all imports should be done relatively to this point.

https://docs.vlang.io/modules.html

> In V, every file is a module.
> The module name is the same as the file name, minus the .v extension.
> To import a module in V, you use the import keyword followed by the module name.
> The module name is the same as the directory path where the module file is located, relative to the root of your project. 

With these considerations `crystallib/examples` directory should be `crystallib/crystallib/examples` unless I miss something and the dev env should be configured differently (?)

**Edit:**
The dev env need to respect specific configuration defined here (https://github.com/freeflowuniverse/crystallib?tab=readme-ov-file#alternative-with-manual-git-checkout--v-install) to be able to run examples without import error.

~~~sh
mkdir -p ~/code/github/freeflowuniverse
cd ~/code/github/freeflowuniverse
git clone git@github.com:freeflowuniverse/crystallib.git
cd crystallib
~~~

**Comment by renauter** [comment]
About fixing `~/code/github/freeflowuniverse/crystallib/examples/tfgrid/grid/examples/vm_high_level/deploy_vm_high_level.v`

After running:
~~~sh
cd crystallib
v -enable-globals run examples/tfgrid/grid/examples/vm_high_level/deploy_vm_high_level.v
~~~

There were some errors, I made some changes (branch: https://github.com/freeflowuniverse/crystallib/tree/development_tfgrid_fixes) and was able to deploy VM on node 129 devnet:
- dashboard:
![image](https://github.com/freeflowuniverse/crystallib/assets/73958772/06a6c842-a828-425e-8191-6169c124b89b)
- polkadot UI:
![image](https://github.com/freeflowuniverse/crystallib/assets/73958772/ccb4760b-63e3-4ff6-8590-fca8419f1fa2)

I will have a look to other examples...

**Comment by renauter** [comment]
About `griddriver` https://github.com/threefoldtech/web3gw/tree/development_integration/griddriver
It is the go component that enables to make calls to tfchain from tfgrid V client via  `TFPluginClient`.
An installer is already available here https://github.com/threefoldtech/web3gw/blob/development_integration/griddriver/build.sh

Example of flow is:
1. `deploy_single_vm()` (crystallib):https://github.com/freeflowuniverse/crystallib/blob/2a32f1fb3962e8374c1b5660de3168365cb8010a/crystallib/threefold/griddriver/utils.v#L14
2. `griddriver cli` (web3gw): https://github.com/threefoldtech/web3gw/blob/7b291e07919a22fee9793e7e01c3cd2f3f74639c/griddriver/main.go#L409
3. `TFPluginClient` (web3gw): https://github.com/threefoldtech/web3gw/blob/7b291e07919a22fee9793e7e01c3cd2f3f74639c/griddriver/network.go#L51
4. `TFPluginClient` (tfgrid-sdk-go): https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/deployer/tf_plugin_client.go
5. `deployers` (tfgrid-sdk-go): 
https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/deployer/network_deployer.go
https://github.com/threefoldtech/tfgrid-sdk-go/blob/development/grid-client/deployer/deployment_deployer.go

**Comment by renauter** [comment]
First version of `griddriver` installer was made here: 
https://github.com/freeflowuniverse/crystallib/blob/development_tfgrid_fixes/crystallib/installers/tfgrid/griddriver/griddriver.v

Maybe found some V issue by running following .vsh script:
~~~vlang
#!/usr/bin/env -S v -w -enable-globals run

import freeflowuniverse.crystallib.installers.tfgrid.griddriver as griddriverinstaller

mut reset:=true
griddriverinstaller.install(reset:reset)!
~~~

See issue here:

![image](https://github.com/freeflowuniverse/crystallib/assets/73958772/8eedd213-ff77-465c-ba3c-3b9896812d6d)

Solved by running:

~~~sh
sudo chmod 1777 /tmp/execscripts 
~~~

**Comment by renauter** [comment]
Fixing examples in `~/code/github/freeflowuniverse/crystallib/examples/tfgrid/grid/`:

- [x] ./utils/zos_version.vsh
- [x] ./utils/get_contracts.vsh
- [x] ./utils/cancel_contracts.vsh
- [x] ./utils/billing_hourly.vsh
- [x] ./utils/deploy_vm_high_level.vsh
- [x] ./utils/cancel_contract.vsh
- [x] ./utils/list_gateways.vsh
- [x] ./tests/vm_with_gw_name.vsh
- [x] ./tests/deploy_gw_name.v
- [x] ./tests/deploy_gw_fqdn.v
- [x] ./tests/deploy_zdb.v
- [x] ./tests/deploy_vm.v
- [x] ./tests/holochain_vm.v
- [x] ./tests/create_update_deployments.v

**Comment by renauter** [comment]
On tfgrid V client I have this error `could not verify signature` when calling the `griddriver` with the `rmb` option
https://github.com/freeflowuniverse/crystallib/blob/ee95868e8c183f5415ea5d3be7385bb4d83b8fdb/crystallib/threefold/griddriver/rmb.v#L7
Most above examples are not running because of this.

Seems it goes through `web3gw` repo
https://github.com/threefoldtech/web3gw/blob/7b291e07919a22fee9793e7e01c3cd2f3f74639c/griddriver/rmb.go#L47

And finally to `rmb-sdk-go` repo and failed here
https://github.com/threefoldtech/tfgrid-sdk-go/blob/61e07567a9306fe6b242bdad2b58066f8c209f1b/rmb-sdk-go/peer/sig.go#L125

Here is an example of a raw command that returns the error:
~~~sh
griddriver rmb --cmd 'zos.system.version' --dst '22' --payload '""' --substrate 'wss://tfchain.dev.grid.tf/ws' --mnemonics 'xxx' --relay 'wss://relay.dev.grid.tf'
~~~

Should be specific to rmb client because `griddriver deploy-single`  option, which uses https://github.com/threefoldtech/tfgrid-sdk-go/tree/development/grid-client, still works.

After discussing with team it seems that `griddriver` is outdated and should follow the changes in `rmb-sdk-go` repo.

Versions in `griddriver` are:

> github.com/threefoldtech/tfgrid-sdk-go/grid-client v0.11.2
> github.com/threefoldtech/tfgrid-sdk-go/rmb-sdk-go v0.11.2

Should be changed to last v0.15.10 and update code.

**Comment by renauter** [comment]
Worked on PR https://github.com/threefoldtech/web3gw/pull/212 to update the `griddriver`. 
Once merged and `griddriver` re-installed the examples should work again.

**Comment by despiegk** [comment]
make sure there is a builder for the driver or at least instrucitons,

**Comment by renauter** [comment]
Also reviewing and adjusting the `grid-proxy` examples

**Comment by renauter** [comment]
Here is a list of the updated examples in `~/code/github/freeflowuniverse/crystallib`:

### Using `griddriver`

#### Deploy

- grid/deploy/create_update_deployments.vsh `Znet` `Zmount` `PublicIP` `Zmachine` `Zlogs` `Zdb` `GatewayNameProxy`
- grid/deploy/deploy_gw_fqdn.vsh `GatewayFQDNProxy`
- grid/deploy/deploy_gw_name.vsh `GatewayNameProxy`
- grid/deploy/deploy_vm_high_level.vsh `VM`
- grid/deploy/deploy_vm.vsh `Znet` `Zmachine`
- grid/deploy/deploy_zdb.vsh `Zdb`
- grid/deploy/holochain_vm.vsh (mycelium) `Znet` `PublicIP` `Zmachine`
- grid/deploy/vm_with_gw_name.vsh (mycelium) `Znet` `PublicIP` `Zmachine` `GatewayNameProxy`

#### Utils

- grid/utils/cancel_contract.vsh
- grid/utils/cancel_contracts.vsh
- grid/utils/tfgrid_config.vsh
- grid/utils/zos_version.vsh

### Using `gridproxy`

#### Explore

- gridproxy/easy/billing_hourly.vsh
- gridproxy/easy/contract.vsh
- gridproxy/easy/farm.vsh
- gridproxy/easy/gateways.vsh
- gridproxy/easy/list_gateways.vsh
- gridproxy/easy/get_contracts.vsh (+griddriver)
- gridproxy/easy/node.vsh
- gridproxy/easy/node_box_poc.vsh
- gridproxy/easy/simple.vsh
- gridproxy/easy/stats.vsh
- gridproxy/easy/twin.vsh

#### Find nodes

- gridproxy/get_nodes/get_nodes_by_capacity.vsh
- gridproxy/get_nodes/get_nodes_by_city_country.vsh
